let shopItemsData = [
    {
        id: "jfhgbvnscs",
        name: "Casual Shirt",
        price: 45,
        desc: "                                                   ",
        img: "images/img-1.jpg",
    },
    {
        id: "ioytrhndcv",
        name: "Office Shirt",
        price: 100,
        desc:  "                                                   ",
        img: "images/img-2.jpg",
    },
    {
        id: "wuefbncxbsn",
        name: "T Shirt",
        price: 25,
        desc:  "                                                   ",
        img: "images/img-3.jpg",
    },
    {
        id: "thyfcbcv",
        name: "Mens Suit",
        price: 300,
        desc:  "                                                   ",
        img: "images/img-4.jpg",
    },
    {
        id: "jfhgbvnscss",
        name: "Casual Shirt",
        price: 69,
        desc:  "                                                   ",
        img: "images/img-5.jpg",
    },
    {
        id: "jfhgbvnscsss",
        name: "Casual Shirt",
        price: 29,
        desc:  "                                                   ",
        img: "images/img-6.jpg",
    },
    {
        id: "jfhgbvnscsww",
        name: "Casual Shirt",
        price: 54,
        desc:  "                                                   ",
        img: "images/img-7.jpg",
    },
    {
        id: "jfhgbvnscsıhbnm",
        name: "Mens Suit",
        price: 110,
        desc:  "                                                   ",
        img: "images/img-8.jpg",
    },
    {
        id: "jfhgbvnscssddfgdv",
        name: "Mens Suit",
        price: 99,
        desc:  "                                                   ",
        img: "images/img-9.jpg",
    },
    {
        id: "jfhgbvnscsqrınd",
        name: "Mens Suit",
        price: 35,
        desc:  "                                                   ",
        img: "images/img-10.jpg",
    },
    {
        id: "jfhgbvnscsohbjk",
        name: "T Shirt",
        price: 150,
        desc:  "                                                   ",
        img: "images/img-11.jpg",
    },
    {
        id: "jfhgbvnscslmhjn",
        name: "T Shirt",
        price: 75,
        desc:  "                                                   ",
        img: "images/img-12.jpg",
    },
    {
        id: "jfhgbvnscsdggnjmkuy",
        name: "T Shirt",
        price: 89,
        desc:  "                                                   ",
        img: "images/img-13.jpg",
    },
];